# Generated by Django 5.2.14 on 2026-05-27 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Weight of the scrap in kilograms.",
                        max_digits=10,
                    ),
                ),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("sold", "Sold")],
                        default="available",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_date"],
            },
        ),
        migrations.CreateModel(
            name="ScrapSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                (
                    "sale_price_per_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "ordering": ["-sale_date"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.DeleteModel(
            name="ScrapInventory",
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["material_name"]},
        ),
        migrations.RemoveConstraint(
            model_name="material",
            name="unique_material_per_supplier",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="updated_at",
            new_name="last_update",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="name",
            new_name="material_name",
        ),
        migrations.RemoveField(
            model_name="material",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="material",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="material",
            name="reorder_level",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="address",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="material",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who added or last updated this material.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="min_stock",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minimum stock level before a low-stock alert is raised.",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("material_added", "Material Added"),
                    ("material_updated", "Material Updated"),
                    ("material_deleted", "Material Deleted"),
                    ("scrap_recorded", "Scrap Recorded"),
                    ("scrap_sold", "Scrap Sold"),
                    ("stock_adjusted", "Stock Adjusted"),
                    ("supplier_added", "Supplier Added"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=("material_name", "material_type", "supplier"),
                name="unique_material_per_supplier",
            ),
        ),
        migrations.AddField(
            model_name="scrap",
            name="material",
            field=models.ForeignKey(
                help_text="The source material this scrap was cut from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraps",
                to="inventory.material",
            ),
        ),
        migrations.AddField(
            model_name="scrapsale",
            name="scrap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="inventory.scrap",
            ),
        ),
        migrations.AddField(
            model_name="scrapsale",
            name="sold_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who processed this sale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrap_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
    ]
