# Generated by Django 5.2.14 on 2026-05-27 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_scrap_scrapsale_remove_product_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("material_added", "Material Added"),
                    ("material_updated", "Material Updated"),
                    ("material_deleted", "Material Deleted"),
                    ("scrap_recorded", "Scrap Recorded"),
                    ("scrap_sold", "Scrap Sold"),
                    ("stock_adjusted", "Stock Adjusted"),
                    ("supplier_added", "Supplier Added"),
                    ("delivery_received", "Delivery Received"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                ("material_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("size", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("received", "Received")],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
