# Generated by Django 5.2.14 on 2026-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_auditlog_action_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                default="other",
                help_text="Material type. Use a preset value or a custom label.",
                max_length=100,
            ),
        ),
    ]
