# Generated by Django 5.2.14 on 2026-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_material_type_free_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("material_added", "Material Added"),
                    ("material_updated", "Material Updated"),
                    ("material_deleted", "Material Deleted"),
                    ("scrap_recorded", "Scrap Recorded"),
                    ("scrap_sold", "Scrap Sold"),
                    ("stock_adjusted", "Stock Adjusted"),
                    ("supplier_added", "Supplier Added"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
    ]
