# Generated by Django 5.2.14 on 2026-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_auditlog_action_delete_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("material_added", "Material Added"),
                    ("material_updated", "Material Updated"),
                    ("material_deleted", "Material Deleted"),
                    ("scrap_recorded", "Scrap Recorded"),
                    ("scrap_sold", "Scrap Sold"),
                    ("stock_adjusted", "Stock Adjusted"),
                    ("supplier_added", "Supplier Added"),
                    ("config_updated", "Configuration Updated"),
                ],
                max_length=30,
            ),
        ),
    ]
