# Generated by Django 5.2.14 on 2026-06-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_add_supplier_address_and_config_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapsale",
            name="quantity_sold",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Weight sold in kilograms.",
                max_digits=10,
            ),
        ),
    ]
