# Generated by Django 5.2.17 on 2026-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_scrapsale_quantity_sold_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('material_added', 'Material Added'), ('material_updated', 'Material Updated'), ('material_deleted', 'Material Deleted'), ('scrap_recorded', 'Scrap Recorded'), ('scrap_claimed', 'Scrap Claimed for Production'), ('scrap_sold', 'Scrap Sold'), ('stock_adjusted', 'Stock Adjusted'), ('supplier_added', 'Supplier Added'), ('supplier_updated', 'Supplier Updated'), ('supplier_deleted', 'Supplier Deleted'), ('config_updated', 'Configuration Updated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed for Production'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
