"""
================================================================
  CutWise IMS - AI Chat View (RAG Pipeline)
  Capstone 2: AI Service — Gemini LLM Integration

  Architecture Mapping (Arch 1):
    Analytics/AI Layer -> AI Service -> LLM Integration -> NL Queries

  Pipeline:
    User Question
      -> [1] Embed with sentence-transformers (all-MiniLM-L6-v2)
      -> [2] ChromaDB semantic search (top 5 materials)
      -> [3] Fetch KPI summary from analytics.db
      -> [4] Build context + system prompt
      -> [5] Gemini 1.5 Flash generates answer
      -> [6] Return { reply, sources[], model }

  Endpoint:
    POST /api/v1/analytics/chat/
    Body: { "message": "Which materials need reorder?" }
    Auth: Bearer JWT (IsAuthenticated)
================================================================
"""

import os
import sqlite3
import logging
from pathlib import Path

from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status

logger = logging.getLogger(__name__)

BASE_DIR        = Path(__file__).resolve().parent.parent.parent
SQLITE_PATH     = BASE_DIR / "data" / "analytics.db"
CHROMA_DIR      = BASE_DIR / "data" / "chroma_db"
COLLECTION_NAME = "cutwise_materials"

# ─── Module-level singletons (loaded once at startup, not per request) ────────

_chroma_collection = None   # ChromaDB collection handle
_embed_model       = None   # SentenceTransformer model
_gemini_client     = None   # Gemini API client


_chroma_count_cache = 0  # tracks last known doc count; non-zero triggers refresh if changed


def _get_chroma_collection():
    """
    Return (and cache) the ChromaDB collection.
    Auto-refreshes the handle when the doc count changes after a vector rebuild —
    so Django doesn't need a restart after running vector_db.py.
    """
    global _chroma_collection, _chroma_count_cache
    try:
        import chromadb
        client = chromadb.PersistentClient(path=str(CHROMA_DIR))
        col = client.get_collection(COLLECTION_NAME)
        current_count = col.count()

        # Refresh if first load OR if collection was rebuilt with new docs
        if _chroma_collection is None or current_count != _chroma_count_cache:
            _chroma_collection = col
            _chroma_count_cache = current_count
            logger.info(f"ChromaDB collection loaded/refreshed: {current_count} documents")

    except Exception as e:
        logger.warning(f"ChromaDB not available: {e}")
        _chroma_collection = None

    return _chroma_collection



def _get_embed_model():
    """Return (and cache) the SentenceTransformer model. Loaded once on first call."""
    global _embed_model
    if _embed_model is not None:
        return _embed_model
    try:
        from sentence_transformers import SentenceTransformer
        _embed_model = SentenceTransformer("all-MiniLM-L6-v2")
        logger.info("SentenceTransformer model loaded")
    except ImportError:
        logger.warning("sentence-transformers not available — will use SQLite fallback")
        _embed_model = None
    return _embed_model


def _get_gemini_client():
    """Return (and cache) the Gemini API client. Created once on first call."""
    global _gemini_client
    if _gemini_client is not None:
        return _gemini_client
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        return None
    try:
        from google import genai
        _gemini_client = genai.Client(api_key=api_key)
        logger.info("Gemini client initialized")
    except Exception as e:
        logger.error(f"Gemini client init failed: {e}")
        _gemini_client = None
    return _gemini_client


# ─── System Prompt ────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are CutWise AI, an intelligent inventory assistant built for Otto Shoes' CutWise Inventory Management System (IMS).

Your role is to help inventory managers, supervisors, and admins understand their leather material stock, risk levels, supplier performance, and reorder needs.

Business context:
- Otto Shoes is a leather goods manufacturer in the Philippines
- Materials tracked: cowhide, goatskin, sheepskin, suede, nappa, synthetic leather
- Currency: Philippine Peso (PHP / ₱)
- Risk levels: CRITICAL (stock at/below minimum, immediate reorder) | HIGH (reorder within 3 days) | MEDIUM (monitor closely) | LOW (adequate stock)
- Forecasts are generated by Linear Regression models using audit log activity as a consumption proxy

Answer guidelines:
- Be concise and actionable (2–4 sentences; use a short bullet list if listing materials)
- Reference specific material names, quantities, and risk levels from the context provided
- Suggest practical actions: reorder, monitor, contact supplier, etc.
- If the context doesn't have enough data to answer, say so clearly
- Never fabricate inventory data not present in the context
- Use ₱ for peso amounts
"""


# ─── Analytics DB Helpers ─────────────────────────────────────────────────────

def get_kpi_summary() -> dict | None:
    """Fetch the latest KPI summary row from analytics.db."""
    if not SQLITE_PATH.exists():
        return None
    try:
        conn = sqlite3.connect(str(SQLITE_PATH))
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM summary_reports ORDER BY run_date DESC LIMIT 1"
        ).fetchone()
        conn.close()
        return dict(row) if row else None
    except Exception as e:
        logger.warning(f"KPI summary fetch failed: {e}")
        return None


# ─── Vector Search ────────────────────────────────────────────────────────────

def _sqlite_fallback_materials(n_results: int = 5) -> list[dict]:
    """
    Fallback: fetch highest-risk materials from analytics.db directly via SQL.
    Used when sentence-transformers is not available in the current venv.
    """
    if not SQLITE_PATH.exists():
        return []
    try:
        conn = sqlite3.connect(str(SQLITE_PATH))
        conn.row_factory = sqlite3.Row
        rows = conn.execute("""
            SELECT
                rm.material_id, rm.material_name, rm.material_type,
                rm.supplier_name, rm.stock_status, rm.quantity, rm.min_stock,
                rm.unit_cost,
                rs.risk_level, rs.at_risk,
                mp.reorder_recommended, mp.days_until_min_stock
            FROM raw_materials rm
            LEFT JOIN risk_scores rs ON rm.material_id = rs.material_id
            LEFT JOIN material_predictions mp ON rm.material_id = mp.material_id
            ORDER BY rs.risk_score DESC
            LIMIT ?
        """, (n_results,)).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception as e:
        logger.warning(f"SQLite fallback failed: {e}")
        return []


def semantic_search_materials(query: str, n_results: int = 5) -> list[dict]:
    """
    Embed the query and retrieve top-N semantically similar materials
    from the ChromaDB collection populated by vector_db.py.
    Uses cached singletons — no per-request model loading.
    Falls back to SQL risk-score ordering if dependencies unavailable.
    """
    collection = _get_chroma_collection()
    if collection is None:
        return _sqlite_fallback_materials(n_results)

    count = collection.count()
    if count == 0:
        return _sqlite_fallback_materials(n_results)

    n_results = min(n_results, count)

    embed_model = _get_embed_model()
    if embed_model is None:
        return _sqlite_fallback_materials(n_results)

    try:
        query_embedding = embed_model.encode([query]).tolist()
        results = collection.query(
            query_embeddings=query_embedding,
            n_results=n_results,
            include=["documents", "metadatas", "distances"],
        )
    except Exception as e:
        logger.error(f"Vector search failed: {e}")
        return _sqlite_fallback_materials(n_results)

    output = []
    ids       = results["ids"][0]
    distances = results["distances"][0]
    metadatas = results["metadatas"][0]
    documents = results["documents"][0]

    for rid, dist, meta, doc in zip(ids, distances, metadatas, documents):
        output.append({
            "material_id":         rid,
            "material_name":       meta.get("material_name", ""),
            "material_type":       meta.get("material_type", ""),
            "supplier_name":       meta.get("supplier_name", ""),
            "stock_status":        meta.get("stock_status", ""),
            "quantity":            meta.get("quantity", 0),
            "min_stock":           meta.get("min_stock", 0),
            "unit_cost":           meta.get("unit_cost", 0),
            "risk_level":          meta.get("risk_level", "UNKNOWN"),
            "at_risk":             meta.get("at_risk", False),
            "reorder_recommended": meta.get("reorder_recommended", False),
            "days_until_min_stock": meta.get("days_until_min_stock", 999),
            "document":            doc,
            "similarity":          round(1 - dist, 4),
        })

    return output



# ─── Context Builder ──────────────────────────────────────────────────────────

def build_context(materials: list[dict], summary: dict | None) -> str:
    """
    Compose a structured context string to inject into the LLM prompt.
    Includes the KPI dashboard summary + top relevant materials.
    """
    lines = []

    if summary:
        lines.append("=== INVENTORY KPI SUMMARY ===")
        total_val = float(summary.get("total_inventory_value") or 0)
        lines.append(f"Total Materials: {summary.get('total_materials', 'N/A')}")
        lines.append(f"Total Inventory Value: ₱{total_val:,.2f}")
        lines.append(f"Materials At Risk: {summary.get('materials_at_risk', 'N/A')}")
        lines.append(
            f"Stock Status — In Stock: {summary.get('in_stock_count', 0)} | "
            f"Low Stock: {summary.get('low_stock_count', 0)} | "
            f"Out of Stock: {summary.get('out_of_stock_count', 0)}"
        )
        avg_days = summary.get("avg_days_to_min_stock", "N/A")
        lines.append(f"Avg Days to Min Stock: {avg_days}")
        lines.append(f"Reorder Recommended: {summary.get('reorder_recommended_count', 0)} materials")
        lines.append("")

    if materials:
        lines.append("=== MOST RELEVANT MATERIALS (vector search results) ===")
        for i, m in enumerate(materials, 1):
            reorder = "YES — REORDER NOW" if m.get("reorder_recommended") else "No"
            days = m.get("days_until_min_stock", 999)
            days_str = (
                "Already below minimum" if days <= 0
                else (f"{int(days)} days" if days < 999 else "Stable")
            )
            status_clean = m.get("stock_status", "").replace("_", " ").title()
            lines.append(
                f"{i}. {m['material_name']} ({m['material_type']})"
                f" | Qty: {m['quantity']} units | Min: {m['min_stock']}"
                f" | Risk: {m['risk_level']}"
                f" | Status: {status_clean}"
                f" | Days to Min Stock: {days_str}"
                f" | Reorder: {reorder}"
                f" | Supplier: {m.get('supplier_name', 'N/A')}"
            )
        lines.append("")

    if not materials and not summary:
        lines.append("No inventory context available. Analytics database may not be populated.")

    return "\n".join(lines)


# ─── Chat Endpoint ────────────────────────────────────────────────────────────

@api_view(["POST"])
@permission_classes([IsAuthenticated])
def analytics_chat(request):
    """
    POST /api/v1/analytics/chat/

    Request:
        {
            "message":      "Which materials are critically low on stock?",
            "page_context": "criticalCount=7, highCount=2"   # optional
        }

    Response:
        {
            "reply":             "Based on current inventory...",
            "sources":           [ { material_name, risk_level, quantity, ... } ],
            "model":             "gemini-1.5-flash",
            "context_materials": 5
        }
    """
    message      = (request.data.get("message")      or "").strip()
    page_context = (request.data.get("page_context") or "").strip()
    if not message:
        return Response(
            {"error": "message field is required and cannot be empty."},
            status=status.HTTP_400_BAD_REQUEST,
        )

    # ── Validate env ──────────────────────────────────────────────────────────
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        return Response(
            {
                "error": (
                    "GEMINI_API_KEY not configured. "
                    "Add GEMINI_API_KEY=<your-key> to backend/.env and restart Django."
                )
            },
            status=status.HTTP_503_SERVICE_UNAVAILABLE,
        )

    if not SQLITE_PATH.exists():
        return Response(
            {
                "error": (
                    "Analytics database not found. "
                    "Run: python -m apps.analytics.extract_data"
                )
            },
            status=status.HTTP_503_SERVICE_UNAVAILABLE,
        )

    # ── Step 1: Vector retrieval ──────────────────────────────────────────────
    try:
        materials = semantic_search_materials(message, n_results=5)
    except Exception as e:
        logger.error(f"Vector search error: {e}")
        materials = []

    # ── Step 2: KPI summary ───────────────────────────────────────────────────
    summary = get_kpi_summary()

    # ── Step 3: Build context ─────────────────────────────────────────────────
    context = build_context(materials, summary)

    # ── Step 4: Call Gemini (cached client — no per-request init) ────────────
    gemini = _get_gemini_client()
    if gemini is None:
        return Response(
            {"error": "GEMINI_API_KEY not configured or google-genai not installed."},
            status=status.HTTP_503_SERVICE_UNAVAILABLE,
        )

    try:
        # Inject optional page context (sent by AIAssistantFloat when alerts are active)
        page_ctx_line = (
            f"\nUser's current dashboard context: {page_context}\n"
            if page_context else ""
        )
        full_prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"Here is the current CutWise inventory context:\n\n"
            f"{context}\n"
            f"{page_ctx_line}"
            f"User question: {message}\n\n"
            f"Answer based on the context above. Be concise and actionable."
        )

        response = gemini.models.generate_content(
            model="gemini-flash-latest",
            contents=full_prompt,
        )
        reply_text = response.text

    except Exception as e:
        logger.error(f"Gemini API error: {e}")
        return Response(
            {"error": f"AI service temporarily unavailable: {str(e)}"},
            status=status.HTTP_503_SERVICE_UNAVAILABLE,
        )

    # ── Step 5: Build source cards ────────────────────────────────────────────
    sources = [
        {
            "material_name":       m["material_name"],
            "material_type":       m["material_type"],
            "risk_level":          m["risk_level"],
            "quantity":            m["quantity"],
            "min_stock":           m["min_stock"],
            "stock_status":        m["stock_status"],
            "reorder_recommended": m["reorder_recommended"],
            "similarity":          m["similarity"],
        }
        for m in materials[:3]  # top 3 as source cards
    ]

    return Response({
        "reply":             reply_text,
        "sources":           sources,
        "model":             "gemini-1.5-flash",
        "context_materials": len(materials),
    })
